# Starter pipeline
- task: DockerCompose@1
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure for Students(c5052511-73be-4a84-9efe-89c1c6a00ee5)'
    dockerComposeFile: '**/docker-compose-dep.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up --build --no-start'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
