version: '3.8'
services:
  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: tiendavideojuegos

    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
  webapp:
    image: tomcat:10-jdk17-temurin-jammy
    container_name: webapp
    volumes:
      - ./target/tienda.war:/usr/local/tomcat/webapps/tienda.war
    restart: always
    ports:
      - 8080:8080