version: '3.8'
services:
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: tiendavideojuegos
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "8080:8080"
    depends_on:
      - database
